broadinstitute/seqr-loading-pipelines

entire_vds_pipeline.py
VCF output capability has been requested from collaborators and is necessary for Mike to run the final step in the seqr upload pipeline to make the samples available in the UI. The pipeline currently needs to match sample IDs in the VCF with what's in seqr; and after remapping sample IDs in the VDS (and, by extension, the elasticsearch database) we need to provide that script with a VCF with the remapped sample IDs.
Filtering to non-ref variants will reduce the elasticsearch table sizes.
=> Adding VCF output capability; plus filtering to non-ref variants only after subsetting samples

gcloud_dataproc/run_script.py, gcloud_dataproc/run_script_GRCh37.py, gcloud_dataproc/run_script_GRCh38.py
Currently, run_script.py, run_script_GRCh37.py, and run_script_GRCh38.py all accept a project argument but ignore it and pass "seqr-project" as the project argument to their create cluster and submit scripts.
=> Use project argument in run script scripts

hail_scripts/load_clinvar_to_es_pipeline.py, hail_scripts/utils/computed_fields.py
Added `transcript_id_to_consequence_json` field with values like:
```
{"ENST00000263253": "missense_variant", "ENST00000634787": "upstream_gene_variant", "ENST00000637592": "downstream_gene_variant"}
```
The full clinvar schema is now:
=> Added transcript consequence mapping for clinvar track

hail_scripts/v02/utils/computed_fields/variant_id.py
The Hail 0.2 equivalent of:
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/cd9ebb47ce435693e98753d03688ef6b3598b102/hail_scripts/v01/utils/computed_fields.py#L352-L355
=> Add function to get variant IDs of original alt alleles in a split variant

gcloud_dataproc/submit.py, hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/utils/computed_fields.py, hail_scripts/v01/utils/vds_utils.py
A new `transcript_rank` field is also computed for every vep annotation. 
It's intended to be used for sorting the transcripts during queries and, for example, only returning the top matching transcript using the inner hits 'sort' and 'size' params  (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html#_options)
=> add --dont-export-to-elasticsearch-until-the-end and --use-nested-objects-for-vep options

hail_scripts/v02/utils/computed_fields/vep.py
Add `transcript_rank` field to `sortedTranscriptConsequences`. This field contains the consequence's index in the list of all sorted consequences for the variant.
=> Add rank field to sorted transcript consequences

hail_scripts/v02/utils/computed_fields/__init__.py, hail_scripts/v02/utils/computed_fields/flags.py, hail_scripts/v02/utils/computed_fields/vep.py
To avoid having to retrieve all transcript consequences from Elasticsearch, precompute flags which are shown in the browser.
Matching this behavior from gnomad_browser:
https://github.com/macarthur-lab/gnomad_browser/blob/b4ff2705fd540037acc31f234f660b26162f5207/utils.py#L95-L109
=> Add helpers to precompute browser LoF flags

hail_scripts/v02/utils/computed_fields/flags.py
Currently, in the gnomAD browser, the "LC LoF" and "LoF Flag" flags are shown for a variant only if **all** the variant's transcript consequences are not HC or flagged, respectively.
@konradjk pointed out that on the gene and transcript pages, these flags should be based only on the variant's consequences in that gene or transcript.
https://macarthurlab.slack.com/archives/C02A348ML/p1542398082164000
Based on a variant's sorted transcript consequences, these functions compute the set of gene IDs where the variant should be flagged.
=> Add functions to compute genes where variants should be flagged

hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/utils/vds_utils.py
Manta vcf loading (eg. dataset_type == 'SV') broke due to relatively recent changes. This fixes it again in a way that shouldn't affect GATK callset loading (eg. dataset_type == 'VARIANTS')
=> fix Manta vcf loading 

hail_scripts/v02/utils/computed_fields/vep.py
This annotation was specific to the gnomAD browser. The browser no longer relies on the presence of the "NC" annotation, so it can be removed from this shared function.
See macarthur-lab/gnomadjs#364 for details.
=> Remove NC LoF annotations

hail_scripts/v02/utils/computed_fields/vep.py
For completeness with https://ensembl.org/info/genome/variation/prediction/predicted_data.html.
Document source of consequence term order as suggested in https://github.com/macarthur-lab/hail-elasticsearch-pipelines/pull/97#issuecomment-456536691.
=> Add start_retained_variant to consequence term list

hail_scripts/v02/utils/computed_fields/variant_id.py, hail_scripts/v02/utils/hail_utils.py
We're now on our third different implementation of the expression for original alt alleles.
The Hail 0.1 version used `contig` and `altAlleles`:
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/1719af96cfb5a06c5b41a2c5244657803c8a22df/hail_scripts/v01/utils/computed_fields.py#L374-L377
Originally, the Hail 0.2 version used `old_locus` and `old_alleles` (fields created by [hl.methods.split_multi](https://hail.is/docs/0.2/methods/genetics.html?highlight=split#hail.methods.split_multi)), assuming `get_expr_for_original_alt_alleles_set` would be run after `split_multi`:
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/eb809528f25f9c055bf50fcca129873df473d23e/hail_scripts/v02/utils/computed_fields/variant_id.py#L23-L29
#82 changed that to use `locus` and …
=> Remove original alt alleles function

hail_scripts/v02/utils/computed_fields/flags.py, hail_scripts/v02/utils/computed_fields/test_flags.py
Related to macarthur-lab/gnomadjs#369.
Currently, the gnomAD browser flags variants with "LC LoF" and "LOF Flag" based on **all** the variant's transcript consequences. This is appropriate for the region page, but flags on the gene and transcript pages need to be based only on transcript consequences in the selected gene or transcript.
This adds functions to compute flags for the transcript page, based on a single transcript consequence.
=> Add helpers for transcript consequence level flags

download_and_create_reference_datasets/v02/hail_scripts/write_splice_ai_ht.py
Another day, another reference dataset. V01: https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/download_and_create_reference_datasets/v01/hail_scripts/write_splice_ai_vds.py
Pretty standard, added some minor tweaks and style changes here and there but core logic should be similar.
- Downloaded the 2.5 GB files for 37, truncated them to 5000 lines, and ran locally.
```
> mt.describe()
----------------------------------------
Global fields:
None
----------------------------------------
Column fields:
's':     str 
----------------------------------------
Row fields:
'locus':     locus<GRCh37> 
'alleles':     array<str> 
'rsid':     str 
'qual':     float64 
'filters':     set<str> 
'info':     struct {
SYMBOL: str, 
STRAND: str, 
TYPE: str, 
DIST: int32, 
DS_AG: …
```
=> splice-ai v02

download_and_create_reference_datasets/v02/create_ht__1kg.py, download_and_create_reference_datasets/v02/create_ht__eigen.py, download_and_create_reference_datasets/v02/create_ht__primate_ai.py
Eigen, 1kg, and Primate AI according to @bw2 are simple load VCF and export to table and that's why they don't have a corresponding v01 file. 
What I did was use https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/download_and_create_reference_datasets/v02/create_ht__mpc.py which is a standard load and dump on the mpc data as template, and copied over the corresponding reference dataset.
None since it's so simple and easier to test on the live data. Will need to learn how to do this.
=> eigen, 1kg, primate_ai

hail_scripts/v02/load_dataset_to_es.py
In response to my closed PR https://github.com/macarthur-lab/hail-elasticsearch-pipelines/pull/104/files#diff-353468bbf478d1b65c009e7b68b607e3R1, the new strategy is to get an identical v02 load_dataset_to_es.py merged to master, and subsequent PRs will only see the relevant v02 changes.
=> v02 load_dataset_to_es and vds_utils equivalents

download_and_create_reference_datasets/v02/hail_scripts/write_dbnsfp_ht.py
A port of https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/download_and_create_reference_datasets/v01/hail_scripts/write_dbnsfp_vds.py to V02 (refer for logic comparison). Since this is a small enough file and is only run once, I did a rewrite so some manual validation has to be done. 
1. Only focused on 2.9.3 because I could not find the directory location for 3.5, so assumed it wasn't used.
2. Fields logic:
- The old code has a data structure that contains all of the fields of the file, with a `---` for the fields that are not needed. It extracts the ignored fields, drops it, and then remaps the names (e.g. `#chr` => `chr`) .
- I decided we don't need to keep track of the ignored fields? Instead, we just keep track of the needed fields with the types, and do a …
=> reference data write dbsnfp v02

hail_scripts/v02/load_clinvar_to_es.py, hail_scripts/v02/utils/computed_fields/test_variant_id.py, hail_scripts/v02/utils/computed_fields/variant_id.py
Currently, the functions for contig, contig number, and xpos all accept a Table/MatrixTable and return a value derived from the `locus` field of that table. However, for some datasets (such as a table of regions with start/stop positions) it would be useful to calculate xpos for fields other than `locus`.
This changes the functions for contig, contig number, and xpos to accept a LocusExpression instead of a Table so that they can be used on any field.
It also changes `get_expr_for_contig` to remove the "chr" prefix from contigs so that `get_expr_for_contig_number` and `get_expr_for_xpos` will work with GRCh38 loci.
=> Change contig/xpos functions to accept a locus instead of a table

gcloud_dataproc/submit.py
Quick fix for delete-temp-nodes issue:
`gcloud dataproc jobs submit` returns a non-zero exit code if the dataproc pipeline crashes. 
This fix then also crashes  `submit.py` so that wrapper scripts (like `load_dataset.py`) can exit without running cleanup steps like delete-temp-loading-nodes and leaving intermediate data for reruns.
=> crash submit.py if `gcloud dataproc jobs submit` exit code != 0

download_and_create_reference_datasets/v02/hail_scripts/write_dataset_validation_ht.py, hail_scripts/v02/utils/computed_fields/vep.py
Another day, another data set. This is the validation data set used in seqr to validate the incoming variants https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/hail_scripts/v01/utils/validate_vds.py#L43.
It wasn't a lot of code and isn't run often, so I decided to do an almost 1 to 1 port of https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/download_and_create_reference_datasets/v01/hail_scripts/write_dataset_validation_kt.py.
v01: 
```
> hc.read_table('gs://seqr-reference-data/GRCh37/validate_vds/common_noncoding_variants.grch37.kt').count()
- 1880L
```
v02:
```
> hl.read_table('gs://seqr-kev/combined-test/validation-noncoding.ht').count()
- 2243
```
v01: 
```
> hc.read_table('gs://seqr-reference-data/GRCh37/validate_vds/common_coding_varian …
```
=> seqr write validation ht

luigi_pipeline/README.md, luigi_pipeline/lib/model/base_mt_schema.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/tests/model/test_base_model.py, luigi_pipeline/tests/model/test_seqr_mt_schema.py, luigi_pipeline/tests/test_seqr_loading_tasks.py
tldr;
Fun stuff, introducing matrix table schemas
- clearly define annotation schema with fields and their values
- centralized so the logic is clearer
- express dependencies between annotations
- allow different types of schema to share annotation definitions but branch
- more easy to do validations and ensure correctness (TODO, with hail and ES types)
**----- The sell ----**
Are you like me, folks? Do you find yourself having a hard time tracking all of the seqr annotations across a long pipeline and from many different sources? Sometimes different tables storing different data should have slightly different annotations while sharing common ones, but the branching logic is just scattered. Other times, annotations depend on other annotations, so you have to order them. Introducing schema …
=> seqr models

luigi_pipeline/lib/model/base_mt_schema.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/tests/model/test_base_model.py, luigi_pipeline/tests/model/test_seqr_mt_schema.py, luigi_pipeline/tests/test_seqr_loading_tasks.py
- bug fix for row_annotations decorator (save some state to instance and not class)
- removed SV schema for now until needed
- added multi_annotation boolean to row_annotations decorator so we can support annotating num_samples_gq_i_to_n more easily (I thought of writing each out, which I actually prefer so it's defined, but there are just so many...)
- Tested against v01 implementation, where we found discrepancies in missing genotypes discussion https://discuss.hail.is/t/hail-v01-to-v02-missing-genotypes/939 and https://hail.zulipchat.com/. Pending consensus, but for non-missing genotypes, computations match. 
- Wrote tests cases off of one variant in the 1kg30
It's a lot of changes, so I'll only tag people in parts that they might be familiar with.
=> v02 genotypes

download_and_create_reference_datasets/v02/hail_scripts/write_clinvar_ht.py, download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py, luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading.py
-Added reference data annotations to seqr loading pipeline which should allow for end to end runs. Tested full runs of SeqrVCFToMTTask locally and on the cloud. Spot checked results but will complete more thorough testing once reference schema is created. 
-Added the gold_star annotations to the write_clinvar_ht script and ran it. https://console.cloud.google.com/dataproc/jobs/a85d98ed6a334547959e3a51760a9c98?project=seqr-project&organizationId=548622027621&supportedpurview=project&region=global&duration=P4D 
-Updated ES port parameter from a string to an int
-Removed unnecessary 'AD' field from gnomad genome coverage reference field selection
-Added all reference data annotations to seqr_mt_schema includes: cadd, dbnsfp, eigen, gnomad_exomes, gnomad_exomes_coverage, gnomad_genomes, …
=> Join mega ref, clinvar, and hgmd tables into seqr mt schema

luigi_pipeline/load_dataset_v02.py
Cloudtools updated their submit script to have pass through args, --args and quotes are no longer necessary.
=> Updated cluster submit to have pass through args

hail_scripts/v02/utils/elasticsearch_client.py, luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py
-Added docId as ES mapping ID to get rid of duplicate docs in index
-ES will skip writing  null fields so added write_null_es_fields arg to write out doc fields that have null values
-Updated error message for subsetting. Originally was printing out the number of samples in the vcf instead of the number of subset samples. This has been fixed. 
-Addressed glob patterns for importing vcfs so luigi requires will not fail
=> Updated docId and null write fields in ES index

hail_scripts/v02/utils/computed_fields/variant_id.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_loading_optimized.py
The long lost forgotten annotations, thanks to @mike-w-wilson validation. 
The important thing to note is `split_multi_hts` drops `old_locus` and `old_alleles` so we might see if we can remove that https://github.com/hail-is/hail/blob/e40fb8901ff40f3e29660cf4ef1193cd2be0f116/hail/python/hail/methods/statgen.py#L2251. In the mean time, we preannotate before splitting to generate the original alt alleles.
=> missing annotations

luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_loading_optimized.py
Solved the problem where unsuccessful runs were returning a 0 (successful) exit code so dataproc thinks it's a success. 
e.g. https://console.cloud.google.com/dataproc/jobs/pyspark_export_project_test_proj_20190815_7e8d25a1?organizationId=548622027621&project=seqr-project&supportedpurview=project&region=global
```
===== Luigi Execution Summary =====
Scheduled 3 tasks of which:
* 2 complete ones were encountered:
- 1 SeqrVCFToGenotypesMTTask(...)
- 1 SeqrVCFToVariantMTTask(...)
* 1 failed:
- 1 SeqrMTToESOptimizedTask(source_path=, use_temp_loading_nodes=True, es_host=10.36.1.2, es_port=9200, es_index=test_proj__WES__grch37__variants__vcfv1__20190815)
This progress looks :( because there were failed tasks
===== Luigi Execution Summary =====
```
Had to dig deep into the code base but turns …
=> exit status code

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_loading_optimized.py
The Elastic Search index was missing some index metadata fields that are added from the matrix table globals through https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/hail_scripts/v02/utils/elasticsearch_client.py#L38.
The Missing and required annotations were `sourceFilePath`, `genomeVersion`, and `sampleType` from https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/00838a882d3e7df40194f915786802c26c9b4cd6/hail_scripts/v01/load_dataset_to_es.py#L309-L311. (I Don't think `dataset` is needed.)
This PR combines the logic that the plain and optimized tasks use to write a matrix table and ensures that the globals are annotated. When they are exported to ES (in the optimized, the variant mt is joined with the project-genotypes mt but the globals are …
=> add globals

luigi_pipeline/lib/model/base_mt_schema.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading.py
We want to make hgmd optional to run locally per @bw2's request.
- Introduces a RowAnnotationOmit exception (inspired by Airflow's https://github.com/apache/airflow/blob/master/airflow/exceptions.py#L73) that can be raised within an annotations function to skip an annotation altogether. 
- We omit the hgmd annotation altogether if no hgmd dataset is provided
=> introduce row annotation skip and make hgmd optional

luigi_pipeline/configs/optimized_configs/seqr-loading-local.cfg, luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_loading_optimized.py
**Problem**: now that we checkpoint mt table to not redo work (e.g. if `variants.mt` exists, it will skip the task as complete), we run into issues if the task failed half way and the mt directory exists but is incomplete. In that case, we want to re-run the task.
This overrides the `complete` [method](https://luigi.readthedocs.io/en/stable/api/luigi.task.html#luigi.task.Task.complete) which by default checks if the output files exist. Instead, we check for the `_SUCCESS` file within the mt. Thus, if incomplete that file will not exist and it will re-run.
We also change the `mt.write` to override in case of incomplete tables.
=> _SUCCESS check

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_loading_optimized.py
Added logic for the number of shards: greater of user specified min_num_shards and a calculated value based on `(variants*samples)/2147483519` translated to `int((mt.count_rows() * mt.count_cols())/2147483519)`. 
NOTE: I don't know where `2147483519` comes from, it was just given to me, it's slightly less than 2^31. Should I use `(2^31 - 2^10) = 2147482624 ` just to make sure we have a larger num shards? 
I tested this locally on the 1kg30 dataset (which as expected calculated the shards to be 0 since the data is so small), but have not run that formula on actual data like RGP. @mike-w-wilson we should do that to make sure that formula gives us what we expect. 
Piggybacked on this PR to add the hail version to the global annotations --> ES metadata.
Optional, but make the min_num_shards …
=> min num shards

hail_scripts/v02/utils/elasticsearch_utils.py
When exporting a table to Elasticsearch, the ES index is created (or updated) with a [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) based on the table's row value. However, the row value does not include key fields. So key fields are currently [dynamically mapped](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_dynamic_mapping). This usually results in fields getting set to the [text](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html) type (and analyzed) when they would preferably be [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html).
This changes the export function to determine the Elasticsearch mapping based on an unkeyed copy of the table. This maps the …
=> Determine ES mapping based on unkeyed table

luigi_pipeline/seqr_loading_optimized.py
Supposedly 0.2.20 should have fixed it. 
Original PR https://github.com/macarthur-lab/hail-elasticsearch-pipelines/pull/166
=> remove agg hack

hail_scripts/v02/utils/elasticsearch_utils.py
Currently, an Elasticsearch mapping can not be generated for a table that contains a [locus](https://hail.is/docs/0.2/types.html#hail.expr.types.tlocus) field.
For example, this code throws a `NotImplementedError`.
```python
import hail as hl
from hail_scripts.v02.utils.elasticsearch_utils import elasticsearch_schema_for_table
ds = hl.utils.range_table(10)
ds = ds.annotate(locus=hl.locus("1", ds.idx))
mapping = elasticsearch_schema_for_table(ds)
print(mapping)
```
This change adds support for the locus type. With this change, that example code outputs:
```
{'idx': {'type': 'integer'}, 'locus': {'type': 'object', 'properties': {'contig': {'type': 'keyword'}, 'position': {'type': 'integer'}}}}
```
=> Add support for locus types in Elasticsearch mapping

hail_scripts/v02/update_models/update_mt_schema.py, hail_scripts/v02/update_reference_data_in_existing_index.py
First, rather raw adapted scripting for ES index update. Further code clean up may be needed: differentiation between GRCh37 and GRCh38, additional config files, etc. The script can be run the following way:
`PYTHONPATH=/opt/seqr/hail-elasticsearch-pipelines/luigi_pipeline:$PYTHONPATH python -u gcloud_dataproc/submit.py  --cpu-limit 4 --num-executors 3 --driver-memory 2g --executor-memory=4g --hail-version 0.2 --run-locally hail_scripts/v02/update_reference_data_in_existing_index.py --index-name $INDEX_NAME --genome-version 37 --update-hgmd --host $ES_HOST --port $ES_PORT`
=> update ES index mechanism

hail_scripts/v02/utils/elasticsearch_client.py
When `export_globals_to_index_meta` is set to true, `export_table_to_elasticsearch` adds the table's globals to the Elasticsearch mapping in the `_meta` field.
However, if one of the global fields contains a struct value, creating the Elasticsearch index  / updating the mapping will fail because the Elasticsearch client can not convert a [hail.utils.Struct](https://hail.is/docs/0.2/utils/index.html#hail.utils.Struct) object to JSON.
This change recurses through the globals struct and converts any struct fields to dicts, which the Elasticsearch client can handle.
=> Convert struct fields in table globals to dict

download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py
This adds in a fallback to gnomAD global AF for a variant when POPMAX AF is not available. This was tested on the variant chr4-73258424-G-T in gnomAD v3 (4-74124141-G-T in gnomAD v2) where the missing value was discovered.
=> Fixed POPMAX_OR_GLOBAL fallback value

gcloud_dataproc/load_dataset.py, kubernetes/elasticsearch-sharded/es-namespace.yaml, kubernetes/kubectl_utils.py, luigi_pipeline/load_dataset_v02.py, luigi_pipeline/load_dataset_v02_optimized.py
Running `load_dataset_v02` with the new `--use-seqr-loading-optimized-pipeline` flag should be equivalent to previously running `load_dataset_v02_optimized` (which this PR deletes). 
The only difference is `load_dataset_v02_optimized` had disabled the `_wait_for_data_nodes_state` method for unclear reasons:
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/master/luigi_pipeline/load_dataset_v02_optimized.py#L143
I didn't add that to `load_dataset_v02 --use-seqr-loading-optimized-pipeline` but may need to if there are issues related to `_wait_for_data_nodes_state`.
=> add --use-seqr-loading-optimized-pipeline to optionally switch to optimized workflow

luigi_pipeline/lib/hail_tasks.py
The subset message was printing the incorrect number. The filtering agg stops now as soon as it finds a non_ref GT instead of checking every GT in a row.
=> Fixed subset message and added small optimization

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading.py
This adds a `rg37_locus` to 38 callsets. Anything that does not lift is currently missing as you can't assign anything but a locus at this annotation. I could add in a `lifted_under` annotation or something if seqr needs a separate field indicating success.
=> add 37 coordinates

download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py, download_and_create_reference_datasets/v02/hail_scripts/write_splice_ai_ht.py, luigi_pipeline/lib/model/seqr_mt_schema.py
This updates spliceAI to the latest data release and adds in the splice consequence term. When there is no max delta score, "No consequence" is the annotated term. This PR also includes an update to including the "was_split" annotation on ES export. I apologize for the format changes, I ran black.
=> Updating spliceAI to have consequence term

luigi_pipeline/lib/hail_tasks.py, sv_pipeline/exome/load_data.py, sv_pipeline/genome/load_data.py, sv_pipeline/genome/load_data_tests.py
small shards create a huge memory overhead and minor search performance decrease, so if data fits in one shard we should do that
=> set lower minimum num shards

hail_scripts/v02/utils/elasticsearch_client.py, sv_pipeline/genome/load_data.py
When the ES is running in a docker container, it could incorrectly get the internal container IP for the address of the ES node rather than the one that can be accessed externally. Add 'nodes.wan.only' can solve the problem. See [the reference](https://discuss.elastic.co/t/get-org-elasticsearch-hadoop-rest-eshadoopnonodesleftexception-connection-error-check-network-and-or-proxy-settings-all-nodes-failed-tried/79509).
=> Add 'nodes.wan.only' parameter to export_table_to_elasticsearch()

CHANGELOG.md, hail_scripts/shared/elasticsearch_client_v7.py, luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_loading_optimized.py
This adds a waiting step for the shard transfer for all projects except RGP. Not hardcoding this bit is probably ideal but I was trying to take the manual step out of the airflow config. The code was based off of v01 but I changed the logger.info to logger.warning because we recently changed Airflow's logging config to warn. I debated increasing the wait time to 10 but stuck with 5 in the end. Happy to change if there are strong opinions. I tested this with this pipeline version: gs://seqr-luigi/releases/optimized-v1.4.5.test/ and the dataproc job is here: https://console.cloud.google.com/dataproc/jobs/pyspark_export_project_R0449_pathways_mgh_20210723_01d8d1ec?region=global&authuser=0&project=seqr-project 
This also adds a changelog to the repo.
=> Add cleanup step to  wait for shard transfer

sv_pipeline/genome/load_data.py, sv_pipeline/genome/load_data_tests.py
Changed the field name `sample_qs_{X}_to_{Y}` to `samples_qs_{X}_{Y}` (add an `s`).
=> Fixed the names for sample qs fields

sv_pipeline/genome/load_data.py, sv_pipeline/utils/common.py
The file name for the sample IDs is usually internally generated. But it is more convenient if it can also be provided with the command line argument.
=> Added id-file command line argument to overwrite the built-in id file path

sv_pipeline/genome/load_data.py
To support separated GQ sliders for Exome and Genome SV searches, we need to rename the samples_qs_X_to_Y field.
=> Change samples_qs_X_to_Y to samples_gq_sv_X_to_Y.

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/lib/model/base_mt_schema.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading_optimized.py
The following fields are disabled: 
`'aIndex', 'alt', 'AN', 'codingGeneIds', 'contig', 'docId', 'domains', 'end', 'geno2mp', 'genotypes', 'gnomad_exome_coverage', 'gnomad_genome_coverage', 'mainTranscript', 'originalAltAlleles', 'pos', 'ref', 'rg37_locus', 'sortedTranscriptConsequences', 'start', 'transcriptIds', 'wasSplit', 'xstart', 'xstop'`
=> disabled field indices that are not necessary

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/lib/model/base_mt_schema.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading_optimized.py
Reverts broadinstitute/hail-elasticsearch-pipelines#280 . The ES export code manipulates the field names by flattening them and replacing `.` with `_` . I believe line 224 in the code needs to be updated to mimic that behavior: https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/3260f4c9e7777a3f158000189c9191f2da384b64/hail_scripts/elasticsearch/hail_elasticsearch_client.py#L131
If we think this is a quick fix, we can close this PR but if not I think we revert.
=> Revert "disabled field indices that are not necessary"

luigi_pipeline/requirements.txt
The requirements.txt is used to build a docker image for local seqr users to run this pipeline, and the pinned version of hail is pretty old and is now causing bugs (https://github.com/broadinstitute/seqr/issues/2460)
=> bump minimum required hail version

hail_scripts/elasticsearch/elasticsearch_client_v7.py
Our exports are failing because ES released a 8.0.0 python package which doesnt recognize port anymore. This pins us to 7.9.1 which is the same as our requirements file for local installs. Hail also only supports 6.X and 7.x for now.
=> Pin ES to 7.9.1

download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py
This PR changes to the names of _hom fields under gnomad_mito and removes the helix AC fields.
=> Rename _hom fields and remove Helix AC fields.

hail_scripts/utils/hail_utils.py
https://github.com/broadinstitute/hail-elasticsearch-pipelines/issues/265
Fixes NaN gene conversion error with grc37 projects
=> Add tolerate_parse_error=True for grc37 projects

luigi_pipeline/lib/model/seqr_mt_schema.py
The way we have to grab all annotations when joining locus and allele keyed tables to interval key tables generates a list of structs containing the annotations. The original implementation maintained this list for gnomAD noncoding constraint zscore however the list contained a single element so this change just grabs that element or returns missing for empty lists.
=> Grab first element of zscore list

docker/Dockerfile, docker/README.md
Updates the pipeline runner docker image to copy files instead of calling git clone. This solves the issue that docker will cache the "giit clone" command even though the files have changed. This way, docker's caching logic will actually check if files changed when determining whether or not to use the cache
=> copy needed files instead of git clone for pipeline runner docker image

download_and_create_reference_datasets/v02/hail_scripts/write_clinvar_ht.py
The current script writes clinvar into a single partition table. This severely impacts the first step of the pipeline. Repartitioning the table to 100 partitions in its creation will increase pipeline speed by taking advantage of spark.
=> Repartition the clinvar HT

luigi_pipeline/requirements.txt
Fix for https://github.com/broadinstitute/seqr-loading-pipelines/pull/625#issuecomment-1822477463.
=> bump the luigi version to 3.4.0

docker/vep_configs/vep-GRCh37-loftee.json, docker/vep_configs/vep-GRCh38-loftee.json
Fasta files are [bgzipped here](https://github.com/broadinstitute/seqr-loading-pipelines/blob/aed106c8250b527197b39ddc6374d85b2942b673/docker/bin/download_reference_data.sh#L19C5-L19C5). However, vep-config argument path is plain text.
=> corrected the ref genome paths

docker/Dockerfile
Remove the `-l` parameter to install the htslib for vep.
=> VEP can't open bgzipped ref withot htslib

v03_pipeline/lib/misc/io.py
"naive_coalesce" is "faster", but is causing a terribly unbalanced `lookup` table at the minimum.  Full shuffle seems fine to me here!
=> Use hail's "repartition" instead of "naive_coalesce".

v03_pipeline/lib/misc/io.py, v03_pipeline/lib/misc/validation.py, v03_pipeline/lib/misc/validation_test.py, v03_pipeline/lib/tasks/write_imported_callset.py
We have a single set of AnVIL project that contain duplicate variants.  Literally:
```
In [15]: mt.filter_rows(mt.locus.position == 3834167).GT.show()
+---------------+------------+--------------+==================>  (24 + 1) / 25]
| locus         | alleles    | 'sample_id'.GT |
+---------------+------------+--------------+
| locus<GRCh38> | array<str> | call         |
+---------------+------------+--------------+
| chr1:3834167  | ["T","G"]  | 1|0          |
| chr1:3834167  | ["T","G"]  | 1|1          |
+---------------+------------+--------------+
```
I think also reasonable to just throw an exception here... but that might end up being more work for us in the long run.
=> Distinct variants only

v03_pipeline/lib/tasks/write_imported_callset.py
This is fixing a potential (I'm _99.9%_ sure this hasn't happened, but not 100% sure) issue where:
1) sample type is correctly supplied and the callset passes validation for that sample type
2) a project is re-run with the same callset but with the wrong sample type.  
The wrong sample type will be passed onwards to the project/family tables and will be annotated there.  The data is correct and fine, but I don't think we want to allow that edge case.
=> Add protection against a user supplying the wrong sample type on a re-run.

v03_pipeline/lib/annotations/mito.py, v03_pipeline/lib/annotations/snv_indel_test.py, v03_pipeline/lib/misc/io.py, v03_pipeline/lib/misc/math.py, v03_pipeline/lib/misc/math_test.py, v03_pipeline/lib/misc/sample_entries.py, v03_pipeline/lib/misc/sample_entries_test.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples.py
I definitely forgot to run the ruff format command when I updated the repo lint settings. Now I remember to run `ruff` _and_ `ruff format` every time 😛
=> ruff format entire repo

v03_pipeline/lib/annotations/fields_test.py, v03_pipeline/lib/annotations/shared_test.py, v03_pipeline/lib/model/environment.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples.py, v03_pipeline/lib/vep.py
Our dataproc setup is giving us these env vars for free and hail encourages their use, so we should use them rather than a hard-coded string default.  It's also slightly cleaner for the local install to pass an env var than a luigi arg.
=> prefer env vars for vep path

v03_pipeline/lib/tasks/base/base_hail_table_task.py, v03_pipeline/lib/tasks/reference_data/updated_cached_reference_dataset_query.py
I'm a bit confused about the errors [here](https://console.cloud.google.com/dataproc/jobs/WriteCachedReferenceDatasetQuery_20240319_b5189cc3/monitoring?region=us-central1&project=seqr-project)
for gnomad_qc, namely why the erroring code is executing because the `super().complete()` call should fail
Hopefully these logs will help me
=> add some logging for crdq debugging

v03_pipeline/lib/reference_data/clinvar.py
getting `hail.utils.java.FatalError: HailException: arguments refer to no files: Vector(/tmp/tmprjuly50t.txt.gz).` in test [run](https://console.cloud.google.com/dataproc/jobs/UpdateVariantAnnotationsTableWithUpdatedReferenceDataset_20240325_f33d2bc6/monitoring?region=us-central1&project=seqr-project)
=> try moving clinvar submitter tmp file to gcs before importing

v03_pipeline/lib/reference_data/clinvar.py
make them equal to the clinvar vcf min partitions to hopefully reduce flakiness of the join. this is mostly a guess
yesterday's test [run](https://console.cloud.google.com/dataproc/jobs/UpdateVariantAnnotationsTableWithUpdatedReferenceDataset_20240328_9a449403/monitoring?region=us-central1&project=seqr-project)  succeeded but after multiple attempts
=> change clinvar submitters table partitions

v03_pipeline/lib/misc/sample_ids.py, v03_pipeline/lib/misc/sample_ids_test.py, v03_pipeline/lib/tasks/update_lookup_table.py, v03_pipeline/lib/tasks/update_project_table.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples.py, v03_pipeline/lib/tasks/write_family_table.py, v03_pipeline/lib/tasks/write_metadata_for_run.py, v03_pipeline/lib/tasks/write_new_variants_table.py, v03_pipeline/lib/tasks/write_project_family_tables.py, v03_pipeline/lib/tasks/write_remapped_and_subsetted_callset.py
this was removed from airflow a bit ago and isn't used any longer.  the current behavior is to exclude incomplete families and post them in slack/metadata file, failing if all families are excluded.
=> remove "ignore_missing_samples_when_subsetting"

v03_pipeline/lib/misc/callsets.py, v03_pipeline/lib/tasks/base/base_update.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples_test.py, v03_pipeline/lib/tasks/validate_callset.py, v03_pipeline/lib/tasks/write_imported_callset.py, v03_pipeline/lib/tasks/write_relatedness_check_table.py, v03_pipeline/lib/tasks/write_relatedness_check_table_test.py, v03_pipeline/lib/tasks/write_remapped_and_subsetted_callset.py
* split import and validate
* lint and share function
* ruff
* change dep
* tweak update
* lint
* wrong method
* correct method
* mocks
* change sample type annotation on test
* remove additional row fields
=> Benb/split import and validate (#829)

v03_pipeline/lib/misc/io.py, v03_pipeline/lib/paths.py, v03_pipeline/lib/reference_data/clinvar.py, v03_pipeline/lib/reference_data/clinvar_test.py, v03_pipeline/lib/reference_data/config.py, v03_pipeline/lib/tasks/reference_data/updated_reference_dataset_collection_test.py
- HEAD the clinvar submission summary to get the etag
- if gs://seqr-scratch-temp/clinvar-submissions-{etag}.ht exists, use that
- if not, follow existing flow of getting submissions from ftp, adding an additional step to save imported submissions to gs://seqr-scratch-temp/clinvar-submissions-{etag}.ht
=> use cached clinvar submission table based on etag

v03_pipeline/bin/vep-110-GRCh38.sh
In preparation for supporting GRCh37 on VEP 11190.  This is cleaner anyways:
```
bblanken@wmbbe-67c seqr-loading-pipelines % gsutil ls gs://seqr-reference-data/vep/GRCh38/
gs://seqr-reference-data/vep/GRCh38/AlphaMissense_hg38.tsv.gz
gs://seqr-reference-data/vep/GRCh38/AlphaMissense_hg38.tsv.gz.tbi
gs://seqr-reference-data/vep/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
gs://seqr-reference-data/vep/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.fai
gs://seqr-reference-data/vep/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.gzi
gs://seqr-reference-data/vep/GRCh38/homo_sapiens_vep_110_GRCh38.tar.gz
gs://seqr-reference-data/vep/GRCh38/uORF_5UTR_GRCh38_PUBLIC.txt
gs://seqr-reference-data/vep/GRCh38/vep-GRCh38.json
```
=> Move VEP files from a `110` path to `GRCh38`.  

v03_pipeline/lib/misc/validation.py, v03_pipeline/lib/misc/validation_test.py, v03_pipeline/lib/model/dataset_type.py, v03_pipeline/lib/tasks/validate_callset.py
=> Raise a validation error if there are SNV_INDEL symbolic alleles

v03_pipeline/lib/misc/validation.py, v03_pipeline/lib/misc/validation_test.py, v03_pipeline/lib/model/dataset_type.py, v03_pipeline/lib/tasks/validate_callset.py
* Filter NON_REF and raise a validation error if there are other SNV_INDEL symbolic alleles
* ruff
* wrong sign
* Update validate_callset.py
* Update validate_callset.py
* Adjust error message to use a set
* ruff format
* fix
* ruff
* misc
=> Raise a validation error if there are SNV_INDEL symbolic alleles (#884)

v03_pipeline/lib/reference_data/queries.py
This expands the AF pre-filter table to include another bucket of variants, with an AF between 0.001 and 0.01. This allows us to more strictly prefilter the entries table on searches (like the AIP search) with stricter AF criteria than locus criteria
I am not sure exactly what would have to be run in order to generate this new table, let me know if I need to write anything else to assist with that
=> add stricter AF prefilter option

v03_pipeline/bin/pipeline_worker.py, v03_pipeline/lib/tasks/base/base_loading_run_params.py, v03_pipeline/lib/tasks/base/base_update.py, v03_pipeline/lib/tasks/base/base_write.py, v03_pipeline/lib/tasks/update_lookup_table.py, v03_pipeline/lib/tasks/update_project_table.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples.py, v03_pipeline/lib/tasks/validate_callset.py, v03_pipeline/lib/tasks/write_family_table.py, v03_pipeline/lib/tasks/write_imported_callset.py, v03_pipeline/lib/tasks/write_new_variants_table.py, v03_pipeline/lib/tasks/write_project_family_tables.py, v03_pipeline/lib/tasks/write_remapped_and_subsetted_callset.py, v03_pipeline/lib/tasks/write_variant_annotations_vcf.py
- The `force` option has very confusing and hard to test/maintain logic due to task dependency management overlap between airflow/luigi.
- We don't really need it anymore now that we're using the pedigree/remap hash in the globals.
=> Remove `force` option.

v03_pipeline/bin/dataproc_vep_init.bash, v03_pipeline/bin/download_vep_reference_data.bash, v03_pipeline/bin/vep, v03_pipeline/lib/model/environment.py, v03_pipeline/lib/vep.py
improve consistency with the rest of the directory structure!
=> rename vep data env var

v03_pipeline/lib/misc/gcp.py, v03_pipeline/lib/tasks/dataproc/create_dataproc_cluster.py, v03_pipeline/lib/tasks/dataproc/create_dataproc_cluster_test.py
service account token-ing is required for terra api requests...this gets us credentialed both locally and in dataproc.
=> Add service account credentialing

v03_pipeline/lib/misc/family_loading_failures.py, v03_pipeline/lib/misc/family_loading_failures_test.py, v03_pipeline/lib/misc/pedigree.py
This fixes a regression caused by [this pr](https://github.com/broadinstitute/seqr-loading-pipelines/pull/921/files), which modified the relationship checking behavior for parents that are identified in the pedigree but excluded from loading.  
Originally we excluded those parental ids from the parsed relationships, which did not work in cases where the parental id helped identify sibling pairs.  
This pr preserves the behavior of excluded parents (test case is [here](https://github.com/broadinstitute/seqr-loading-pipelines/blob/main/v03_pipeline/lib/misc/pedigree_test.py#L466)), but also allows us to exclude relationships where the sample is not included as loadable in the pedigree (test case is [here](https://github.com/broadinstitute/seqr-loading-pipelines/pull/1003/files#diff-380bf733d …
=> bugfix: exclude samples from relationship checking that are not present in the expected loadable samples

requirements.in, requirements.txt, v03_pipeline/lib/methods/sample_qc.py, v03_pipeline/lib/tasks/write_sample_qc_json_test.py
adds `qc_gen_anc` and related fields to sample_qc json
=> add ancestry imputation

v03_pipeline/lib/annotations/misc.py, v03_pipeline/lib/reference_datasets/misc.py, v03_pipeline/lib/tasks/base/base_update_variant_annotations_table.py, v03_pipeline/lib/tasks/reference_data/update_variant_annotations_table_with_updated_reference_dataset.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples.py, v03_pipeline/lib/tasks/write_new_variants_table.py
Refactors the reference data/ enums globals creation and it from the annotations update to the new variants creation (then uses the globals from that table!)
=> refactor: add globals to new variants

v03_pipeline/lib/tasks/clickhouse_migration/migrate_all_project_entries_to_clickhouse_test.py, v03_pipeline/lib/tasks/clickhouse_migration/migrate_project_entries_to_clickhouse.py
small oversight, but potentially leading to duplicate loads during the migration!
=> bugfix: ensure family samples are written during migration

v03_pipeline/lib/paths.py, v03_pipeline/lib/paths_test.py, v03_pipeline/lib/tasks/write_sample_qc_json_test.py
Resolves: https://github.com/broadinstitute/seqr-loading-pipelines/issues/1119
=> chore: tweak cache bust logic to use size, accounting for frequently changing modification times
