create_snapshot.py, entire_vds_pipeline.py, list_repositories.py, print_elasticsearch_stats.py, print_snapshot_status.py, register_snapshot_repository.py, restore_snapshot.py, utils/elasticsearch_client.py, utils/elasticsearch_utils.py
pip.main(..) is getting removed in pip v10 - more details here:
https://groups.google.com/forum/#!searchin/pypa-dev/pip.main%7Csort:date/pypa-dev/JVTfS6ZdAuM/6UTolx2bAwAJ
=> replace pip.main(..) with os.system('pip install ..') calls

download_and_create_reference_datasets/hail_scripts/v01/write_cadd_vds.py
Update CADD scores to version 1.4 (#43)
=> Update paths to CADD files to latest version

README.md, hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/update_clinvar_in_existing_index.py, hail_scripts/v01/utils/vds_utils.py
=> make dataset_type match seqr dataset types and add genomeVersion, sampleType, datasetType to index meta

gcloud_dataproc/submit.py, hail_scripts/v01/convert_vcf_to_vds.py, hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/run_vep.py, hail_scripts/v01/update_clinvar_in_existing_index.py, hail_scripts/v01/utils/elasticsearch_client.py, hail_scripts/v01/utils/elasticsearch_utils.py, hail_scripts/v01/utils/hail_utils.py, hail_scripts/v01/utils/vds_utils.py
split  loading pipeline into functions for each step
=> seqr loading pipeline clean up

hail_scripts/v02/utils/elasticsearch_utils.py
=> Map collections of structs to nested objects in ES mapping

hail_scripts/v02/utils/computed_fields/vep.py
To match the behavior of gnomad_browser
https://github.com/macarthur-lab/gnomad_browser/blob/b4ff2705fd540037acc31f234f660b26162f5207/utils.py#L122-L144
macarthur-lab/gnomadjs#225
=> Format hgvs annotation for synonymous variants

hail_scripts/v02/utils/elasticsearch_client.py
After change to Hail's API in https://github.com/hail-is/hail/pull/4387
=> Switch from Expression.value to hl.eval

hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/utils/vds_utils.py
- this adds the --not-gatk-genotypes option for when --dataset-type VARIANTS but VCF genotypes are not in the format GT:AD:DP:GQ:PL
=> add 10x LongRanger vcf support

README.md, gcloud_dataproc/create_cluster_GRCh37.py, gcloud_dataproc/create_cluster_GRCh38.py, gcloud_dataproc/create_cluster_notebook.py, gcloud_dataproc/create_cluster_without_VEP.py, gcloud_dataproc/load_dataset.py, gcloud_dataproc/run_script.py, gcloud_dataproc/run_script_GRCh37.py, gcloud_dataproc/run_script_GRCh38.py, gcloud_dataproc/submit.py, hail_scripts/v01/load_dataset_to_es.py
Otherwise, local installs would have to explicitly set these in all commands.
=> remove --project and --zone settings so that they fall back on gcloud defaults

hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/update_reference_data_in_existing_index.py, hail_scripts/v01/utils/add_clinvar.py, hail_scripts/v01/utils/add_exac.py, hail_scripts/v01/utils/add_hgmd.py, hail_scripts/v01/utils/vds_utils.py, kubernetes/shell_utils.py
- fixes based on feedback for previous PR
- filter to only export variants that have reference data annotations
=> Improve update ref data script

hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/utils/computed_fields.py, hail_scripts/v01/utils/elasticsearch_client.py
Also includes small fixes for child doc genotypes
=> Remove upstream downstream variant annotations

hail_scripts/v02/utils/computed_fields/vep.py
59c03690 applied to the Hail 0.2 version of computed fields.
=> Remove unused VEP fields

CONTRIBUTING.md, hail_scripts/v02/utils/computed_fields/test_flags.py
Tests for functions added in #90.
=> Add tests for LoF flag functions

hail_scripts/v02/utils/computed_fields/vep.py
#87 applied to the Hail 0.2 version of computed fields.
Resolves macarthur-lab/gnomadjs#384.
=> Remove upstream/downstream gene consequence terms

download_and_create_reference_datasets/v01/create_kt__dataset_validation.py, download_and_create_reference_datasets/v01/create_vds__all_variant_level_reference_data.py, download_and_create_reference_datasets/v01/create_vds__cadd.py, download_and_create_reference_datasets/v01/create_vds__clinvar.py, download_and_create_reference_datasets/v01/create_vds__dbnsfp.py, download_and_create_reference_datasets/v01/create_vds__gnomad.py, download_and_create_reference_datasets/v01/create_vds__splice_ai.py, download_and_create_reference_datasets/v01/hail_scripts/combine_all_variant_level_reference_data.py, download_and_create_reference_datasets/v01/hail_scripts/write_splice_ai_vds.py, hail_scripts/v01/load_dataset_to_es.py, hail_scripts/v01/print_vds_stats.py, hail_scripts/v01/update_reference_data_in_existing_index.py, hail_scripts/v01/utils/add_combined_reference_data.py, hail_scripts/v01/utils/add_splice_ai.py
Add precomputed splice prediction scores from https://github.com/Illumina/SpliceAI
=> splice prediction scores

gcloud_dataproc/restore_disks_from_snapshots.py
=> gcloud_dataproc/restore_disks_from_snapshots.py

gcloud_dataproc/load_dataset.py, hail_scripts/v01/load_dataset_to_es.py
updates to docs and logs based on recent debugging
=> Docs and logs

hail_scripts/v01/update_reference_data_in_existing_index.py
This is needed for some local installs.
=> add --dataset-path and --genome-version args to optionally override values in elasticsearch index metadata

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/tests/test_hail_tasks.py, luigi_pipeline/tests/test_seqr_loading_tasks.py
Naming refactor according to https://github.com/macarthur-lab/hail-elasticsearch-pipelines/pull/128
fyi @bw2
=> naming refactor

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/tests/test_hail_tasks.py
Remapping and subsetting tests were also added. Files needed for both are created during the tests.
=> adding subset and remap functionality

download_and_create_reference_datasets/v02/hail_scripts/write_clinvar_ht.py, hail_scripts/v02/utils/clinvar.py
Run and done https://console.cloud.google.com/dataproc/jobs/54bc21eec5a04cefa8deaf80d8a62180?project=seqr-project&supportedpurview=project&organizationId=548622027621&region=global&duration=PT1H
=> clinvar mt to ht

luigi_pipeline/README.md, luigi_pipeline/configs/luigi.cfg, luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/load_dataset_v02.py, luigi_pipeline/seqr_loading.py
Working wrapper script to load dataproc and ES nodes.
- Ported over `load_dataset.py` to `load_dataset_v02.py` with minor changes so we can make progress. Will evaluate whether it's worth it to re-write. (changes usually have `v02` in name of function or in comment. 
- different functions to spin up and submit to dataproc using cloudtools
- in v02 all args sent to `load_dataset.py` is sent to `load_dataset_to_es.py`, but with config files in v02, we only send what's needed (es_host and es_port)
- Minor changes
- added es_host and es_port to es task
- minor bug fixes
FYI @bw2 @hanars @mike-w-wilson
=> v02 loading

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/tests/test_hail_tasks.py
Temp loading nodes switch, a la v01.
Verified with a test cluster and saw that index settings were applied.
fyi @mike-w-wilson @hanars @bw2
=> temp loading node flip

luigi_pipeline/seqr_loading.py
This PR fixes the extra variants we were seeing in previous pipeline runs. Previously multi-allelic splitting was running after subsetting samples which created extra variant entries that were not present in the subsetted samples. Splitting after importing the vcf addresses this.
=> Moved split_multi_hts from after subsetting to after importing the vcf

hail_scripts/v02/export_table_to_es.py
Moving generic parts of the gnomAD browser's data pipelines to this repository.
=> Add script to export Hail table to Elasticsearch

download_and_create_reference_datasets/v02/create_ht__combined_reference_data.py, download_and_create_reference_datasets/v02/create_ht__gnomad_38.py, download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py, download_and_create_reference_datasets/v02/hail_scripts/write_gnomad_38_hts.py
-Added  geno2mp to 37 and 38 ref datasets to config
-Added gnomad 38 liftover and gnomad coverage to 38 configs
=> Add gnomad 38 ref data

hail_scripts/v02/utils/hail_utils.py
Added a 38 config to the vep runner
=> Add 38 config to vep runner

gcloud_dataproc/submit.py, gcloud_dataproc/v02/create_cluster_without_VEP.py, luigi_pipeline/load_dataset_v02.py
-Replaced cloudtools with hailctl for 0.2 loading pipeline
-Updated old dev level hail 0.2 to recent hail 0.2 release
=> Updated hail 0.2 version for hailctl use

luigi_pipeline/lib/model/seqr_mt_schema.py
=> off by one

download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py
Updated gnomAD reference table fields to match v01 ref fields
=> Fixed gnomAD reference fields to match v01 pipeline

luigi_pipeline/lib/model/seqr_mt_schema.py
Forgot to add in the new geno2mp ref annotation in the pipeline after it was added to the reference table. Thanks to @hanars  for the catch!
=> Added geno2mp ref annotation

download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py
Replaces ref 38 gnomad genome with v3 instead of v2.
- separates selector function `custom_gnomad_select_v2` and `custom_gnomad_select_v3`
- fixes 1kg path `1kg.wgs.phase3.20170504.GRCh38_sites_test.ht` to `1kg.wgs.phase3.20170504.GRCh38_sites.ht`
- writes the ht to a separate directory `v2` and versions the file instead of overwriting
- adds to globals (version as well as adds src paths to the dataset so we can see which version of gnomad is used in that ref data)
Checked that `describe` works, if everyone approves will kick this off. Once this is written, we just need to update the ref data location https://github.com/macarthur-lab/All-The-Envs/blob/master/airflow/dags/seqr-vcf-to-es.py#L56
FYI @mike-w-wilson when you get back
=> added gnomad v3 to ref data

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/requirements.txt
Luigi renamed _FrozenOrderedDict => FrozenOrderedDict 2 months ago
https://github.com/spotify/luigi/blame/master/luigi/parameter.py#L43
Fixes #188
=> Update code to work with most recent luigi release

luigi_pipeline/README.md
=> readme change

hail_scripts/v02/utils/hail_utils.py
=> Changed vep config to point to hail configs

luigi_pipeline/lib/hail_tasks.py
motivated by https://github.com/macarthur-lab/seqr/issues/1343
=> make it easier to load VCFs with non-standard chromosome names

sv_pipeline/load_data.py
The Sv loading pipeline did not handles SVs that were in no genes properly which causes downstream bugs in seqr. This fixes that bug and also updates the pipeline to run in python 3
=> Sv missing gene

sv_pipeline/genome/load_data.py
See details in issue: https://github.com/broadinstitute/seqr-private/issues/1019
=> Add sample_qs_{X}_to_{Y} field and update transcriptConsequenceTerms field.

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/seqr_loading.py
This relates to Seqr [issue #1010](https://github.com/broadinstitute/seqr/issues/1010).  It's also an extension to #204 by parameterising the liftover file path.
(cherry picked from commit 2a8a4ebb21f42fe68f12c4ddd20648567d231018)
=> feat: Parameterise 37 coords ref file

sv_pipeline/exome/load_data.py
Updates the exome SV pipeline pipeline to resolve the issue in https://github.com/broadinstitute/seqr/issues/2141
=> sample specific gene ids

sv_pipeline/genome/load_data.py
Add 'rg37_locus_end' for the translocation variants only because some CPX variants have END2 which exceeds the range of the GRCh38 reference genome.
=> Add the 'rg37_locus' and 'rg37_locus_end' fields.

docker/Dockerfile, docker/README.md, docker/bashrc, docker/bin/copy_reference_data_to_gs.sh, docker/bin/download_reference_data.sh, docker/bin/load_data.sh, docker/bin/load_data_dataproc.sh, docker/entrypoint.sh, docker/gitconfig, docker/spark-defaults.conf, docker/vep_configs/vep-GRCh37-loftee-dataproc.json, docker/vep_configs/vep-GRCh37-loftee.json, docker/vep_configs/vep-GRCh38-loftee-dataproc.json, docker/vep_configs/vep-GRCh38-loftee.json
This moves the code for building a pipeline runner image from the seqr repo to this repo. None of this code is seqr specific, so moving the code into this repo is better for maintainability, and also allows us to add cloud build triggers to automatically rebuild the image when relevant files change. Other than the README file I added, everything is directly copied form the seqr repo with no changes
=> add pipeline runner docker image

sv_pipeline/exome/load_data.py, sv_pipeline/utils/common.py
Updates the pipeline to work with the latest (hopefully final) data format for gCNV data delivery
=> gCNV pipeline update

docker/Dockerfile
Update the repo name to be associated with seqr and not hail.
=> Update repo name in docker

luigi_pipeline/lib/model/seqr_mt_schema.py
Disabling broke  interval search, reindexing this field.
=> Reindex the xstop annotation

download_and_create_reference_datasets/v02/hail_scripts/write_combined_reference_data_ht.py, download_and_create_reference_datasets/v02/mito/write_mito_helix_ht.py
See the [issue 2880](https://github.com/broadinstitute/seqr/issues/2880).
I tested in my local dev environment. The population information is displayed as below picture.
=> Add AN field to the Helix reference data.

docker/README.md, docker/vep_configs/vep-GRCh38-loftee.json
Fixes https://github.com/broadinstitute/seqr/discussions/2862#discussioncomment-3503471
I've already built and pushed up the fixed docker image, just committing the change here for posterity/ future updates
=> Fix docker image fasta config

luigi_pipeline/seqr_loading.py
I forgot one commit in my last merge.
=> Fix temp typo

docker/bin/download_reference_data.sh, docker/vep_configs/vep-GRCh37-loftee.json
The updated docker image has already been build and pushed, addresses request from https://github.com/broadinstitute/seqr/discussions/2695#discussioncomment-3790576
=> add fasta file for local install hg37

docker/README.md, docker/bin/load_data_dataproc.sh
Fixes the issues discussed in https://github.com/broadinstitute/seqr/discussions/3069 and https://github.com/broadinstitute/seqr/discussions/3031
I have already built and released the image
=> fix docker build platform and script path

docker/bin/download_reference_data.sh
Fixes https://github.com/broadinstitute/seqr/discussions/3097
Docker image has already been released
=> fix build 37 fasta download

luigi_pipeline/seqr_loading.py
=> adding clinvar version to the callset mt

luigi_pipeline/seqr_loading.py, luigi_pipeline/tests/test_seqr_loading_tasks.py
Resolves #256.
```
PYTHONPATH=.. nosetests tests/test_seqr_loading_tasks.py
LOGGING: writing to /Users/bblanken/Desktop/code/seqr-loading-pipelines/luigi_pipeline/hail-20230217-1129-0.2.109-b71b065e4bb6.log
.......
----------------------------------------------------------------------
Ran 7 tests in 1.865s
OK
```
=> Fix validate mt error messages.

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/lib/model/base_mt_schema.py, luigi_pipeline/lib/model/gcnv_mt_schema.py, luigi_pipeline/lib/model/mito_mt_schema.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/tests/model/test_seqr_mt_schema.py
=> Prefer f-string to c-style

luigi_pipeline/lib/hail_tasks.py, luigi_pipeline/lib/model/gcnv_mt_schema.py, luigi_pipeline/lib/model/mito_mt_schema.py, luigi_pipeline/lib/model/seqr_mt_schema.py, luigi_pipeline/lib/model/sv_mt_schema.py, luigi_pipeline/seqr_gcnv_loading.py, luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_loading_optimized.py, luigi_pipeline/seqr_mito_loading.py, luigi_pipeline/seqr_sv_loading.py, luigi_pipeline/tests/model/test_base_model.py, luigi_pipeline/tests/model/test_seqr_mt_schema.py, luigi_pipeline/tests/test_hail_tasks.py, luigi_pipeline/tests/test_seqr_gcnv_loading.py, luigi_pipeline/tests/test_seqr_loading_tasks.py, luigi_pipeline/tests/test_seqr_sv_loading.py
Upon merge I'll also update the command that zips up `pyscripts.zip`
```
zip pyscripts.zip -r ./luigi_pipeline/lib ./hail_scripts ./luigi_pipeline/seqr_loading.py ./luigi_pipeline/seqr_loading_optimized.py ./luigi_pipeline/__init__.py
```
is the new command.
=> Package up the `luigi_pipeline` directory.

luigi_pipeline/seqr_loading.py, luigi_pipeline/seqr_mito_loading.py
Fixes a bug introduced by directing all of the variants tasks through the same `run` method.
=> multiple dataset types flowing through this method now... be specific when path checking.

hail_scripts/computed_fields/vep.py
This was my best attempt at this, let me know if I'm on the right track!
=> Noncoding exon transcript variants

hail_scripts/computed_fields/vep.py
=> Add exon and intron to transcript consequences

luigi_pipeline/lib/model/sv_mt_schema.py, luigi_pipeline/tests/test_seqr_sv_loading.py
Waiting for a ticket to be sure... but I think this is on the right track!
=> Implement prev_call for sv callset

luigi_pipeline/lib/hail_tasks.py
@mike-w-wilson we talked about this briefly last week.
=> Fewer Hail Operations in remap. 

v03_pipeline/lib/annotations/shared.py, v03_pipeline/lib/annotations/shared_test.py
This is probably partially complete, since I think we have more string cleanup to do here.
=> vep enum mapping updates

luigi_pipeline/seqr_loading.py
Closes https://github.com/broadinstitute/seqr-loading-pipelines/issues/607
=> Filter invalid contigs rather than throw an error, drop `AF` and `PL`.

v03_pipeline/lib/misc/io.py, v03_pipeline/lib/model/dataset_type.py, v03_pipeline/lib/tasks/write_imported_callset.py
addresses https://github.com/broadinstitute/seqr-loading-pipelines/issues/603 plus one more thing of interest.
=> Importing callset bugfixes/tweaks

docker/Dockerfile
Related discussion:
https://github.com/broadinstitute/seqr-loading-pipelines/issues/623#issuecomment-1822719116
https://github.com/broadinstitute/seqr-loading-pipelines/issues/624#issuecomment-1820102168
https://github.com/broadinstitute/seqr-loading-pipelines/issues/624#issuecomment-1820671218
=> packages for hail and psproc and purge the pip cache

download_and_create_reference_datasets/v02/hail_scripts/write_clinvar_ht.py, v03_pipeline/bin/write_cached_reference_dataset_query_ht.py, v03_pipeline/lib/annotations/enums.py, v03_pipeline/lib/misc/io.py, v03_pipeline/lib/model/cached_reference_dataset_query.py, v03_pipeline/lib/model/definitions.py, v03_pipeline/lib/model/definitions_test.py, v03_pipeline/lib/reference_data/clinvar.py, v03_pipeline/lib/reference_data/clinvar_test.py, v03_pipeline/lib/reference_data/combine.py, v03_pipeline/lib/reference_data/config.py, v03_pipeline/lib/reference_data/hgmd.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples_test.py
- also added 'contig_recoding' as a property on ReferenceGenome 
- includes tests for ReferenceGenome enum properties
- moved some clinvar constants to enums.py
=> use ReferenceGenome enum in custom download functions

v03_pipeline/lib/model/definitions.py, v03_pipeline/lib/model/definitions_test.py
hey at least the logging exists so that I could find this bug: https://console.cloud.google.com/dataproc/jobs/UpdateVariantAnnotationsTableWithNewSamplesTask_20240227_619f78e1/monitoring?region=us-central1&project=seqr-project
=> fix contig recoding for 37

v03_pipeline/lib/tasks/reference_data/write_cached_reference_dataset_query.py, v03_pipeline/lib/tasks/reference_data/write_cached_reference_dataset_query_test.py
I forgot to change the base branch to dev, oops
=> merge crdq wrapper task to dev

v03_pipeline/lib/model/cached_reference_dataset_query.py, v03_pipeline/lib/tasks/reference_data/updated_cached_reference_dataset_query.py
seeing 
```
KeyError: "StructExpression instance has no field 'clinvar'\n    Did you mean:\n        'clinvar_mito'\n    Hint: use 'describe()' to show the names of all data fields."
```
in [these](https://console.cloud.google.com/dataproc/jobs/WriteCachedReferenceDatasetQuery_20240319_3489b648/monitoring?region=us-central1&project=seqr-project) dataproc logs
=> fix MITO clinvar crdq

v03_pipeline/bin/write_cached_reference_dataset_query_ht.py
Reverts broadinstitute/seqr-loading-pipelines#738
I want to run this to see if gnomad_qc used to work without the requester pays issue
=> Revert "delete old crdq code"

v03_pipeline/lib/reference_data/config.py
I copied both tables into the new directory!
=> update gnomad_qc source_path

v03_pipeline/lib/tasks/update_variant_annotations_table_with_deleted_families.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_deleted_project.py
Noticed that this was missing!
=> Check for has_lookup_table

requirements.in, requirements.txt, v03_pipeline/lib/misc/validation.py, v03_pipeline/lib/misc/validation_test.py, v03_pipeline/lib/reference_data/config.py, v03_pipeline/lib/tasks/write_imported_callset.py
Hail team fixed this bug: https://github.com/hail-is/hail/issues/14288
=> Fix syntax

v03_pipeline/lib/reference_data/clinvar.py
Resolves: https://github.com/broadinstitute/seqr-loading-pipelines/issues/771
=> cloud agnostic clinvar

v03_pipeline/lib/misc/validation.py, v03_pipeline/lib/misc/validation_test.py, v03_pipeline/lib/tasks/validate_callset_test.py
Resolves: https://github.com/broadinstitute/seqr-loading-pipelines/issues/919
=> Improve allele type validation

v03_pipeline/lib/model/cached_reference_dataset_query.py, v03_pipeline/lib/tasks/reference_data/updated_cached_reference_dataset_query.py
Setup for moving `clinvar` into its own rdc.
=> Make dataset collection reference non hardcoded to COMBINED

v03_pipeline/lib/tasks/dataproc/create_dataproc_cluster.py, v03_pipeline/lib/tasks/dataproc/create_dataproc_cluster_test.py
need to be clearer about this!
=> bugfix: enforce gcloud vars

.github/workflows/prod-release.yml
=> update pipeline-runner helm release action to bump version too

v03_pipeline/lib/paths.py, v03_pipeline/lib/paths_test.py
Resolves: https://github.com/broadinstitute/seqr-loading-pipelines/issues/1022
=> Add modified time to callset path

v03_pipeline/lib/misc/terra_data_repository.py, v03_pipeline/lib/tasks/write_sex_check_table_test.py
tiny PR. updates the existing test that uses the TDR so that the mock biguery rows look most like the actual response.
=> tdr updates for sample qc

.github/workflows/prod-release.yml
prod release failure: https://github.com/broadinstitute/seqr-loading-pipelines/actions/runs/13702513235/job/38319670072
cloudbuild logs: https://console.cloud.google.com/cloud-build/builds;region=global/61b25e9d-af9a-4b60-bb5b-db6b828f149e?project=seqr-project
setup-gcloud action: https://github.com/google-github-actions/setup-gcloud
=> Update prod-release.yml upgrade setup-gcloud action

v03_pipeline/lib/misc/validation.py, v03_pipeline/lib/misc/validation_test.py, v03_pipeline/lib/model/dataset_type.py, v03_pipeline/lib/tasks/validate_callset.py
Resolves https://github.com/broadinstitute/seqr-loading-pipelines/issues/1055
=> validate AD length

v03_pipeline/lib/misc/callsets.py, v03_pipeline/lib/misc/callsets_test.py, v03_pipeline/lib/tasks/update_variant_annotations_table_with_new_samples_test.py, v03_pipeline/var/test/pedigrees/test_pedigree_10.tsv, v03_pipeline/var/test/pedigrees/test_pedigree_11.tsv
this went uncovered in the tests because we don't have a test over multiple SV projects inside a single callset.  Added that test!
=> bugfix:fix incorrect union-ing method of matrix tables.
